apiVersion: v1
kind: Service
metadata:
  labels:
    app: snipe-it
  name: snipe-it
  namespace: "{{ namespaces.snipe_it }}"
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: snipe-it
  type: ClusterIP
status:
  loadBalancer: {}